version: '3'
services:
  imagebot:
    build: .
    command: python3 main.py
    environment: 
      - IMAGE_BOT_API=""
      - PYTHONUNBUFFERED=True
    ports: 
      - "5000:5000" 
    volumes: 
      - ./:/root